# Generated by Django 4.2.1 on 2023-05-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManagement', '0002_alter_address_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='blacklist',
            field=models.BooleanField(default=False),
        ),
    ]
