# Generated by Django 4.2.1 on 2023-05-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManagement', '0006_alter_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
