# Generated by Django 4.2.1 on 2023-06-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManagement', '0007_alter_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='avtar',
            field=models.ImageField(default='', null=True, upload_to='avtar/images'),
        ),
    ]
