# Generated by Django 4.2.1 on 2023-06-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManagement', '0008_contacts_avtar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='avtar',
        ),
        migrations.AddField(
            model_name='contacts',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to='avatar/images'),
        ),
    ]
