# Generated by Django 4.2.1 on 2023-06-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactManagement', '0009_remove_contacts_avtar_contacts_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklisters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contactManagement.contacts')),
            ],
        ),
    ]
