# Generated by Django 4.2.1 on 2023-06-23 04:05

import contactManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactManagement', '0011_alter_blacklisters_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='blacklist',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to=contactManagement.models.upload_to),
        ),
    ]
